USE biblioteca_pessoal_1s2026;

ALTER TABLE usuario
ADD COLUMN senha VARCHAR(255) NOT NULL AFTER email;

ALTER TABLE usuario
MODIFY data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE usuario
ADD COLUMN data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

